### PR TITLE
Update efl-9999.ebuild

### PR DESCRIPTION
**Pull request by azaganidis**
Fix build break 
(lib/ecore_x/xlib/ecore_x_xi2.c :303: _ecore_x_xi2_grabbed_devices_list not declared)

### CODE REVIEW

**Comment by pavlix** [comment]
Have you consulted the need for -j1 with developers at #e IRC Freenode?

**Comment by rafspiny** [comment]
I was having the same problem on my machine yesterday. 
Can you give more details, I am not sure how this can fix the not declared problem.

Thanks

**Comment by anestis89sl1** [comment]
Seems to build fine now, with recent changes on the master, regardless of the flag.

**Comment by rafspiny** [comment]
@pavlix I had the same problem and I had time tonight to take look at the code.

From [here](https://git.enlightenment.org/core/efl.git/plain/src/lib/ecore_x/xlib/ecore_x_xi2.c), I can see
```C
#ifdef ECORE_XI2
#ifdef ECORE_XI2_2
#ifndef XITouchEmulatingPointer
#define XITouchEmulatingPointer (1 << 17)
#endif

typedef struct _Ecore_X_Touch_Device_Info
{
   EINA_INLIST;
   int devid;
   int mode;
   const char *name;
   int max_touch;
   int *slot;
} Ecore_X_Touch_Device_Info;
#endif /* ifdef ECORE_XI2_2 */

static XIDeviceInfo *_ecore_x_xi2_devs = NULL;
static int _ecore_x_xi2_num = 0;
#ifdef ECORE_XI2_2
static Eina_Inlist *_ecore_x_xi2_touch_info_list = NULL;
#endif /* ifdef ECORE_XI2_2 */
static Eina_List *_ecore_x_xi2_grabbed_devices_list;
#endif /* ifdef ECORE_XI2 */
```

The ebuild is explicitly disabling xinput2 with `--disable-xinput2`, so I re-enable it and I was able to compile efl.

Do you know why **xinput2** has been explicitly disabled?

I'm sharing here my experience, but if you prefer to, feel free to move it.

Thanks

**Comment by pavlix** [comment]
@okias Since I abandoned the enlightenment packages, it would be nice to have someone to take care of those in ixit, or to start a new repository just for enlightenment. I'm willing to help someone in the latter case.

**Comment by pavlix** [comment]
@azaganidis Should we close the pull request, then?

**Pull request closed without merging**
